export const FireEffectConfig = {
  count: 5,
  baseScale: 1.75,
  textureSizeLarge: 14,
  textureSizeSmall: 14,
  starPoints: 1,
  velocityX: 2,
  velocityYMin: 0,
  velocityYMax: 0,
  lifeMin: 1,
  lifeMax: 4,
  frameRate: 8,
  randomRotation: false,
  rotationSpeed: 0,
  alphaMax: 0.35,
  pulseSpeed: 0.52,
  pulseAmount: 0.25,
  blendMode: "ADD" as const,
  colorStart: 0xff4400,
  colorEnd: 0xff9900,
} as const;
