export const ParticleConfig = {
  count: 5,
  baseScale: 0.075,
  textureSizeLarge: 0.025,
  textureSizeSmall: 0.01,
  starPoints: 5,
  velocityX: 30,
  velocityYMin: 18,
  velocityYMax: 56,
  lifeMin: 0.64,
  lifeMax: 10,
  frameRate: 8,
  randomRotation: true,
  rotationSpeed: 3,
  alphaMax: 0.95,
  pulseSpeed: 0.25,
  pulseAmount: 0.2,
  blendMode: "ADD" as const,
  colorStart: 0xffe066,
  colorEnd: 0xff6a00,
} as const;
